# apiVersion: v1

# kind: Service

# metadata:
#   name: sparta-node-service

# spec:
#   selector:
#     app: sparta-node-app
#   ports:
#   - port: 3000
#     targetPort: 3000

#   type: LoadBalancer


  
apiVersion: v1
kind: Service
metadata:
  name: mongo-deployment
  labels:
    app: database
spec:
  clusterIP: None
  selector:
    app: database